/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PicnicPointRouteImport } from './routes/picnic-point'
import { Route as RuralCampsRouteImport } from './routes/rural-camps'
import { Route as GalleryIndexRouteImport } from './routes/gallery.index'
import { Route as GallerySlugRouteImport } from './routes/gallery.$slug'
import { Route as ToursSlugRouteImport } from './routes/tours.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PicnicPointRoute = PicnicPointRouteImport.update({
  id: '/picnic-point',
  path: '/picnic-point',
  getParentRoute: () => rootRouteImport,
} as any)
const RuralCampsRoute = RuralCampsRouteImport.update({
  id: '/rural-camps',
  path: '/rural-camps',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const GallerySlugRoute = GallerySlugRouteImport.update({
  id: '/gallery/$slug',
  path: '/gallery/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursSlugRoute = ToursSlugRouteImport.update({
  id: '/tours/$slug',
  path: '/tours/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/picnic-point': typeof PicnicPointRoute
  '/rural-camps': typeof RuralCampsRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/gallery/': typeof GalleryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/picnic-point': typeof PicnicPointRoute
  '/rural-camps': typeof RuralCampsRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/gallery': typeof GalleryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/picnic-point': typeof PicnicPointRoute
  '/rural-camps': typeof RuralCampsRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/tours/$slug': typeof ToursSlugRoute
  '/gallery/': typeof GalleryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/picnic-point'
    | '/rural-camps'
    | '/gallery/$slug'
    | '/tours/$slug'
    | '/gallery/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/picnic-point'
    | '/rural-camps'
    | '/gallery/$slug'
    | '/tours/$slug'
    | '/gallery'
  id:
    | '__root__'
    | '/'
    | '/picnic-point'
    | '/rural-camps'
    | '/gallery/$slug'
    | '/tours/$slug'
    | '/gallery/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PicnicPointRoute: typeof PicnicPointRoute
  RuralCampsRoute: typeof RuralCampsRoute
  GallerySlugRoute: typeof GallerySlugRoute
  ToursSlugRoute: typeof ToursSlugRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picnic-point': {
      id: '/picnic-point'
      path: '/picnic-point'
      fullPath: '/picnic-point'
      preLoaderRoute: typeof PicnicPointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rural-camps': {
      id: '/rural-camps'
      path: '/rural-camps'
      fullPath: '/rural-camps'
      preLoaderRoute: typeof RuralCampsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$slug': {
      id: '/gallery/$slug'
      path: '/gallery/$slug'
      fullPath: '/gallery/$slug'
      preLoaderRoute: typeof GallerySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$slug': {
      id: '/tours/$slug'
      path: '/tours/$slug'
      fullPath: '/tours/$slug'
      preLoaderRoute: typeof ToursSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PicnicPointRoute: PicnicPointRoute,
  RuralCampsRoute: RuralCampsRoute,
  GallerySlugRoute: GallerySlugRoute,
  ToursSlugRoute: ToursSlugRoute,
  GalleryIndexRoute: GalleryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
